name: analytics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - jupyter
  - jupyterlab
  - nbformat # ter voorkoming van 'capture_validation_error' bij openen notebooks
  - nb_conda_kernels
  - ipykernel
  # SPSS inlezen
  - pyreadstat
  # code format
  - black
  - isort
  # database
  - pyodbc
  - sqlalchemy
  # statistiek
  - scikit-learn
  - scipy # ter voorkoming van phik incompatibility
  # excel en arrow
  - pyarrow #nodig voor pandas om parquet in te laden
  - openpyxl
  - xlrd
  # documentatie
  - mkdocs
  # scripting
  - click
  - python-dotenv
  # metadata van dataframes
  - pandas-profiling
  - tangled-up-in-unicode # ter voorkoming van pandas-profiling incompatibility
  # visualisatie
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - altair
  - altair_data_server
  - altair_saver
  - pip
