name: analytics
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair
  - future
  - pyarrow
  - pandas
  - numpy
  - pyodbc
  - sqlalchemy
  - pingouin
  - scikit-learn
  - python=3.8
  - matplotlib
  - bokeh
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - ipykernel
  - openpyxl
  - xlrd
  - pip
  - click
  - python-dotenv
  - altair_data_server
  - altair_saver
  - pip:
     - savReaderWriter
