name: analytics
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - ipykernel
# code format
  - black
  - isort
# database
  - pyodbc
  - sqlalchemy
# statistiek
  - pingouin
  - scikit-learn
# excel en arrow
  - pyarrow
  - openpyxl
  - xlrd
# scripting
  - click
  - python-dotenv
# visualisatie
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - altair
  - altair_data_server
  - altair_saver
  - pip
  - pip:
     - savReaderWriter
