name: analytics
channels:
#  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=1.4
  - numpy
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - ipykernel
# code format
  - black
  - isort
# database
  - pyodbc
  - sqlalchemy
# statistiek
  - pingouin
  - scikit-learn
# excel en arrow
  - pyarrow
  - openpyxl
  - xlrd
# documentatie
  - mkdocs
# scripting
  - click
  - python-dotenv
# standaard project-structuur en pipelines
  - pyyaml=6.0 # nodig voor kedro
  - kedro
# metadata van dataframes
  - pandas-profiling=3.1
# visualisatie
  - matplotlib
  - seaborn
  - plotly
  - bokeh
  - altair
  - altair_data_server
  - altair_saver
  - pip
  - pip:
     - savReaderWriter
