name: hl-analytics
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair
  - anaconda
  - pandas
  - numpy
  - python=3.6
  - matplotlib
  - bokeh
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - ipykernel
  - openpyxl
  - xlrd
  - googlemaps
  - pyarrow
  - pip
  - pip:
     - altair_data_server
