site_name: analytics setup
site_url: https://hl-analytics.github.io/hl-analytics-setup/
repo_url: https://github.com/hl-analytics/hl-analytics-setup
extra_css:
  - css/extra.css
theme:
  name: "mkdocs"
  features:
    - navigation.tabs
  palette:
    primary: red
nav:
  - index.md
  - "Installatie":
      - Installeer Github Desktop: "installatie/installeer_github_desktop.md"
      - Installeer (Anaconda) Python: "installatie/installeer_python.md"
  - "Configuratie":
      - Aanmaken environment: "configuratie/aanmaken_analytics_environment.md"
      - Opstart directory: "configuratie/jupyter.md"
      - Updates: "configuratie/updaten_environment.md"
  - "Aan de slag":
      - Powershell: "aan_de_slag/powershell.md"
      - Werken met environment: "aan_de_slag/werken_met_analytics_environment.md"
