site_name: analytics setup
extra_css:
  - css/extra.css
theme:
  name: "mkdocs"
  features:
    - navigation.tabs
  palette:
    primary: red
nav:
  - index.md
  - "Installatie":
      - "installatie/installeer_github_desktop.md"
      - Installeer (Anaconda) Python: "installatie/installeer_python.md"
  - "Configuratie":
      - Aanmaken analytics environment: "aanmaken_analytics_environment.md"
      - Opstart directory: "jupyter.md"
      - Updates: "updaten_environment.md"
  - "Aan de slag":
      - "powershell.md"
      - "werken_met_analytics_environment.md"
